### PR TITLE
remove colon

### LINKED ISSUE #923: [Bug]: Track/Route filename contains a colon, which causes problems on Android
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Maps app **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a track or route file, default filename contains at least one colon, which makes the file not downloadable/unopenable on Android (and possibly other OSes)

### Steps to reproduce

1. Create a track
2. Try to open it on Android device

### Expected behavior

Unclear errors, renaming the file in Nextcloud fixes this

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install of the server?

Fresh Nextcloud Server install

### Is this bug present after an update or on a fresh install of the app?

Fresh Nextcloud Maps install (never installed before)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bookmarks: 11.0.4
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.4
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.3
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.18
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.2
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.3.2
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.5
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail: 1.14.0
  - richdocumentscode: 22.5.502
  - spreed: 14.0.5
  - user_ldap
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Browser Console

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by tacruc**
fixes #923

### CODE REVIEW

File: src/components/map/routing/RoutingMachine.vue [hunk 1]
```diff
@@ -503,8 +503,8 @@ export default {
 				}
 			})
 			const name = type === 'route'
-				? t('maps', 'Route {date}', { date: moment().format('LLL:ss') })
-				: t('maps', 'Track {date}', { date: moment().format('LLL:ss') })
+				? t('maps', 'Route {date}', { date: moment().format('LLLss') })
```
Comment (zukaitis) [inline src/components/map/routing/RoutingMachine.vue:506]: Will this be enough to also remove a colon between hours and minutes (16:20 for example)?

**Comment by tacruc** [comment]
Ok I see, was a little fast here.
What would be your suggestion, for the name?
Shall we replace : by nothing, or a white space?

**Comment by zukaitis** [comment]
Both are ok, I guess, nothing would look more like military time in 24h format
