### PR TITLE
Fixes #193 - Handle storage exceptions on occ scan import

### LINKED ISSUE #193: manual scanphoto terminated
**Expected:**
manual Scan adds photos to map

**actual:**
scan & add is termininated with error

**Setup:**
- Debian 18.04. with with official updates until 2019-10-14
- PHP 7.3.10
- MariaSQL 10.1.41
- Webserver Apache & nginx proxy
- NC: 16.05
- 8 CPU Cores
- 16 GB RAM

**Used CMD:**
occ $ maps:scan-photos

**CMD Output:**
...
[1274] Photo "/USERNAME1/files/IMG_20180723_203516.jpg" added
[1275] Photo "/USERNAME1/files/IMG_20180723_203539.jpg" added
[1276] Photo "/USERNAME1/files/IMG_20180723_203555.jpg" added
[1277] Photo "/USERNAME1/files/IMG_20180723_203616.jpg" added
======== User USERNAME2 ========
[1] Photo "/USERNAME2/files/Photos/Coast.jpg" added
[2] Photo "/USERNAME2/files/Photos/Hummingbird.jpg" added
[3] Photo "/USERNAME2/files/Photos/Nut.jpg" added
======== User USERNAME3 ========
"\n\u001b[33mIn Availability.php line 90:\u001b[39m\n\u001b[37;41m                                                \u001b[39;49m\n\u001b[37;41m  [OCP\\Files\\StorageNotAvailableException (1)]  \u001b[39;49m\n\u001b[37;41m                                                \u001b[39;49m\n\n\u001b[32mmaps:scan-photos [\u001b[39m\u001b[32m\u003Cuser_id\u003E\u001b[39m\u001b[32m]\u001b[39m\n\n"

**NexcloudLog:**
[PHP] Error: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/SUBSCRIPTIONNAME1/DOMAINNAME1/apps/maps/lib/Command/RescanPhotos.php:75) at /var/www/vhosts/SUBSCRIPTIONNAME1/DOMAINNAME1/lib/private/AppFramework/Http/Output.php#69

POST /index.php/apps/occweb/cmd
from MYipADRESS1 by USERNAME3 at 2019-10-15T11:25:32+00:00

### PR DESCRIPTION
**Pull request by vwbusguy**
Fixes #193 .

Fixes the issue where scans are aborted when some storage or share is unavailable.  This fix instead handles the exception, logs the affected storage, and then continues the scan operation.

### CODE REVIEW

File: lib/Service/PhotofilesService.php [hunk 1]
```diff
@@ -329,7 +329,13 @@ private function gatherPhotoFiles ($folder, $recursive) {
                         continue;
                     }
                 }
-                $notes = array_merge($notes, $this->gatherPhotoFiles($node, $recursive));
+                try {
+                        $notes = array_merge($notes, $this->gatherPhotoFiles($node, $recursive));
+                } catch (\OCP\Files\StorageNotAvailableException | \Exception $e) {
+                        $msg = "WARNING: Could not access " . $node->getName();
```
Comment (vwbusguy) [inline lib/Service/PhotofilesService.php:335]: Giving the affected folder seems more useful than the stack trace which doesn't include it.  In my case, there was an old shared folder with a problem that I didn't know about until I added this message.

File: lib/Service/PhotofilesService.php [hunk 2]
```diff
@@ -329,7 +329,13 @@ private function gatherPhotoFiles ($folder, $recursive) {
...
+                        echo($msg . "\n");
```
Comment (vwbusguy) [inline lib/Service/PhotofilesService.php:336]: The logger doesn't appear to log anything to stdout, so without this echo, it doesn't get reported when this is ran from occ.

File: lib/Service/PhotofilesService.php [hunk 3]
```diff
@@ -329,7 +329,13 @@ private function gatherPhotoFiles ($folder, $recursive) {
...
+                        $this->logger->error($msg);
```
Comment (vwbusguy) [inline lib/Service/PhotofilesService.php:337]: I was on the fence about if this should be an error or a warning.  Since it's possibly that there are tracks or photos in the path that won't get scanned, I left it as error, but I'm happy to change this if you prefer a different level.

File: lib/Service/PhotofilesService.php [hunk 4]
```diff
@@ -329,7 +329,13 @@ private function gatherPhotoFiles ($folder, $recursive) {
                         continue;
                     }
                 }
-                $notes = array_merge($notes, $this->gatherPhotoFiles($node, $recursive));
+                try {
```
Comment (vwbusguy) [inline lib/Service/PhotofilesService.php:332]: Using a try/catch here doesn't fundamentally change anything about the existing code flow.  It just allows us to catch a currently unhandled exception and continue processing other paths rather than breaking for everything if some storage is broken or temporarily unavailable (ie, s3 can't be reached, etc.).

**Comment by tacruc** [comment]
Nice job.
