### PR TITLE
Fix for division by 0 errors. resolves #645

### LINKED ISSUE #645: Division by zero at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#413
{"reqId":"nArEhugwWE2sGg728epV","level":3,"time":"2021-08-07T18:20:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Division by zero at /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php#413","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php","line":413,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Division by zero","/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php",413,{"0":"And 6 more entries, set log level to debug to see all entries","file":{"__class__":"OC\\Files\\Node\\File"},"path":"/media/nextcloud/data/XXX/files/Fotos/XXX/XXX.jpg","has_info":false,"exif":{"0":"And 56 more entries, set log level to debug to see all entries","FileName":"XXX.jpg","FileDateTime":1628359859,"FileSize":3031758,"FileType":2,"MimeType":"image/jpeg"},"LatM":1}]},{"file":"/var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php","line":264,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/nextcloud/apps/maps/lib/BackgroundJob/AddPhotoJob.php","line":56,"function":"addPhotoNow","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},"XXX"]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Maps\\BackgroundJob\\AddPhotoJob","type":"->","args":[{"photoId":12345,"userId":"XXX"}]},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.3.1","id":"61177c3204374"}

### PR DESCRIPTION
**Pull request by kovge**
- Fix Division by 0 Errors in case of incorrect (or fake, missing) Geocoordinate data. 
  In general: All division operatios must be handled since php throws Error exceptions.
- getExifPelBackup could throw some type of Error Exceptions, all are Catched as Throwable.
 In general:  php Throws error exceptions as well (previously they were only warnings or notices) They must be handled like exceptions.
- avoid to have images with 0,0 coordinates

### CODE REVIEW

File: lib/Service/PhotofilesService.php [hunk 1]
```diff
@@ -406,34 +406,33 @@ private function getExif($file) {
...
 
-        if ($has_info) {
-            return $file_object;
-        } else {
-            return null;
+            if (isset($exif["DateTimeOriginal"])) {
+                $file_object->dateTaken = strtotime($exif["DateTimeOriginal"]);
+            }
+        }catch(\Throwable $t){
+            $file_object = null;
```
Comment (tacruc) [inline lib/Service/PhotofilesService.php:433]: @kovge @eneiluj what do you think about logging the \Exception?

**Comment by tacruc** [comment]
Thanks for your PR. I appreciate it as I didn't manage to look into this for a while.

So far I have only  tow minor concerns:

- Technically (0, 0) is a valid coordinate, therefore form some perspective it is wired and quite unsuspected to not show it.  
 On the other hand 0,0 is somewhere in the middle of the ocean and it is unlikely for people to make pictures there. Most 0,0 coordinates are probably create by some kind of "None", "Null" to 0 replacement. 
- If we drop valid coordinates, I think it should be logged as debug or info.

File: lib/Service/PhotofilesService.php (hunk 1 above)
Comment (kovge) [reply lib/Service/PhotofilesService.php:433]: @tacruc 

Thank you for your reply.

You are right 0,0 is a perfectly valid coordinate. The problem is, that if we have empty coordinate values in the image tag,
it is casted to 0.

What do you think, if we do there an empty string check, and only than drop it.

Story:
In my case i just turned off on my "lineageos phone" the geocoordinates. I did the same on my previous phone.
It produced a huge amount if images with coordinates (0,0) or coordinates (,) (empty string) I know that the perfect geocoordiateless image should have no Geocoord Tags, but as an image is also an input as every other thing uploaded by user to the server, it could have dirty data. Not talking about my old Camera
I know that these exif tags are not really exact, there is a fraction definition with the slashes and so on... and even if there are standards, the data we have all around the world fits to a standard in wery rare cases.
I guess logging would be a good idea for unit tests maybe (if we log in non production mode)
Throwing 0,0 Coordinates away, statistically produces a better usage of map, as throwing away some really valid 0,0 geocoordinated images .. 

What is your opinion?

 - Strict Empty string check -> Invalid Value -> we throw this data
 - 0,0 Is valid , but could be hidden from map (maybe a checkbox in the app frontend and a filter on Database level), what do you think?
 - Logging any kind of debug info (even if the exif tags are not present) could be useful in unit tests/dev envirolment as DEBUG message
 - Logging ErrorExceptions we could log (Like division by 0 , file not found ...) like a Warning. So there i could split up the catch to different type of exceptions. (ErrorException, ... , And than as last fallback the \Throwable) For each type of them than it could be decided, if it need to be logged or not, and the log Level) 
 - I agree that we Log as Info if we drop a valid 0,0. 
 - I would really like to prevent, that the Image "crawling" stops caus a dirty image. I mean it is better if he just skip em, than we log an error message regarding the type of catched Throwable, and continue to next image.

If you agree and have a good idea, i am more than happy to implement it here. (VUE is not a problem as well)

If you agree or have a better idea, please tell me, than i push a new code to this pull request

Thank You.

Comment (tacruc) [reply lib/Service/PhotofilesService.php:433]: I think the error handling here can be simple. 
Just something like:
logException($t,['level'=>'info'])

Comment (kovge) [reply lib/Service/PhotofilesService.php]: Hi, i pushed a new commit.
As i seen in code, there was already a "zero island" check.  I outsourced the exif data reading to a Helper class and defined a special exception type from him.
Added a validate function to him, optinally with zero island detextion. 
The new class using more typehints and forces (float) for numbers. I tried to write it as more self explain as possible.
Added notice Logs in case of validation problems, witch comes from the Exif data.
All other Exceptions (or errors) Are logged as error.

Only last thing. as OC 21 Drops php 7.3 compatibility i wrote the new class's properties with 7.4 Syntax witch makes this app not anymore compatible with 7.3. Do you want that we keep it like this, or should i write it backward compatible. It is not a big change there, but i would like to know your opinion.

**Comment by rhtenhove** [comment]
This seems to resolve a bothersome log-filler, and the requirements and additions seem to have been met.

What is keeping this PR from being merged?

**Comment by ciropom** [comment]
I'm also having the same issue on nextcloud 23, I hope this will be merged soon if it solves the issue.

**Comment by LeoColman** [comment]
@tacruc 
Do you need any help with this?

**Comment by kovge** [comment]
> @tacruc Do you need any help with this?

I need that someone reviews it. All other checks passed.
I appriciate for all the feedbacks. I made all the changes we discussed about. Do i miss somethong?

**Comment by kovge** [comment]
Hi, 

I seen a nice pull request regarding to drop php7.3 version compatibility and pull in a composer update of PEL Package:
https://github.com/nextcloud/maps/pull/683
Regarding these changes i might need to retest and change some changes in the: [lib/Helper/ExifGeoData.php](https://github.com/nextcloud/maps/pull/586/files#diff-b61e1377ced1f6a68d605a0036826d010309ea9408d1d261dce56a9d1149a63a) file.
Expecially at line 139, 
[ self::TIMESTAMP => $pelDateTimeOriginal->getValue(PelEntryTime::EXIF_STRING)
](https://github.com/nextcloud/maps/pull/586/files#diff-b61e1377ced1f6a68d605a0036826d010309ea9408d1d261dce56a9d1149a63aR139)
as it throws an error after compsoer update. (Because the getValue does not need and accepts any more parameters)
I have also seen , that someone else was experiencing issues, witch might be solved by this pull request.

Can someone confirm, that if i make these changes, it going to be reviewed and merged somewhen? Is there some braking issues with this pull request, witch prevents the merge?
Thankyou.

**Comment by umgfoin** [comment]
> I seen a nice pull request regarding to drop php7.3 version compatibility and pull in a composer update of PEL Package: #683 Regarding these changes i might need to retest and change some changes 

I dropped 7.3 in [this PR](#683) because:
- 7.3 is [out of support](https://www.php.net/supported-versions.php) since 12/2021
- nextcloud support for maps is defined as ` <nextcloud min-version="20" max-version="24"/>`:
Probably should be set to 21-24 as NC20 is out of support, too.
 Min PHP requirement for NC 21 is PHP 7.3, but already raised to 7.4 in [master](https://github.com/nextcloud/server/blob/50f51b1782ba0fb2c41d6ad232714298d68df2d8/lib/versioncheck.php#L28).

> Can someone confirm, that if i make these changes, it going to be reviewed and merged somewhen? Is there some braking issues with this pull request, witch prevents the merge? Thankyou.

I guess the "breaking issue" is lack of resources...
I can test and review your refactorings for 8.0.x, but merging should be done by the team-members e.g. @tacruc or @eneiluj

++umgfoin.

**Comment by kovge** [comment]
> [umgfoin](/umgfoin)

Hi @umgfoin

yup, it is completely understandable. So i am more than happy, for php8 support and the pel package update.
The current package already caused for me some confusions, because it was not properly working with php8. (lt aready throws some declaration of, and similar php errors in php7.4)
I just mentioned your comment to warn (in first case myself) and the core team, that if the pel package wull be updated i need to change the previously mentioned line in this pull request, otherweise it produces an error.
The current pel package wants there the parameter,
the updated one wants that function call empty.

So i am just waiting for that the php8 + pel update pull request finishes, than i need to merge the new master in this pull request and change the corresponding line.

**Review by tacruc — APPROVED** [review]
Hi @kovge,
thanks for your contribution and patients with the review process.
